<div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <div><?php
        $locale = Mage::getStoreConfig('general/locale/code', Mage::app()->getStore());
        $session = Mage::getSingleton('admin/session');
        $pref_lang = $session->getByjunoLanguage();
        if (empty($pref_lang))
        {
            $pref_lang = 'de';
        }
        $locale = strstr($locale, "_", true);
        $lang = 'de';
        if ($locale == 'de' || $locale == 'fr' || $locale == 'it' || $locale == 'en') {
            $lang = $locale;
        }

        /* @var $quote Mage_Sales_Model_Quote */
        $quote = Mage::getSingleton('adminhtml/session_quote')->getQuote();
        $is_b2b = (Mage::getStoreConfig('payment/cdp/businesstobusiness', Mage::app()->getStore()) == 'enable');
        $pl = Array();
        if ($locale) {
            if ($is_b2b && $quote->getBillingAddress()->getCompany() != "") {
                $pl = Mage::getStoreConfig('payment/cdp/byjuno_invoice_paymentsb2b', Mage::app()->getStore());
            } else {
                $pl = Mage::getStoreConfig('payment/cdp/byjuno_invoice_payments', Mage::app()->getStore());
            }
        }
        $plns = explode(",", $pl);

        $stringValues = Array();
        $tocValues = Array();
        $enablesValues = Array();

        if ($is_b2b && $quote->getBillingAddress()->getCompany() != "") {
            $methodsAllowed["invoice_byjuno_enable"] = Array("byjuno_invoice_payments_invoiceb2b", "byjuno_invoice_payments_invoice_urlb2b");
            $methodsAllowed["invoice_single_enable"] = Array("byjuno_invoice_payments_singleb2b", "byjuno_invoice_payments_single_urlb2b");
        } else {
            $methodsAllowed["invoice_byjuno_enable"] = Array("byjuno_invoice_payments_invoice", "byjuno_invoice_payments_invoice_url");
            $methodsAllowed["invoice_single_enable"] = Array("byjuno_invoice_payments_single", "byjuno_invoice_payments_single_url");
        }

        $i = 0;
        foreach($plns as $val) {
            if (strstr($val, "_enable")) {
                $enablesValues[] = $val;
                $stringValues[] = Mage::getStoreConfig('payment/cdp/'.$methodsAllowed[$val][0], Mage::app()->getStore());
                $tocValues[] = Mage::getStoreConfig('payment/cdp/'.$methodsAllowed[$val][1], Mage::app()->getStore());
            }
        }
        $i = 0;
        $plans = Array();
        foreach($enablesValues as $key => $p) {
            $plans[] = Array("code" => $p, "name" => $stringValues[$key], "toc" => $tocValues[$key]);
            $i++;
        }

        $paperInvoice = Mage::getStoreConfig('payment/cdp/byjuno_invoice_paper', Mage::app()->getStore());
        $logo = 'https://byjuno.ch/Content/logo/de/6639/BJ_Rechnung_BLK.gif';
        switch ($lang) {
            case 'de':
                $logo = 'https://byjuno.ch/Content/logo/de/6639/BJ_Rechnung_BLK.gif';
                break;
            case 'fr':
                $logo = 'https://byjuno.ch/Content/logo/fr/6639/BJ_Facture_BLK.gif';
                break;
            case 'it':
                $logo = 'https://byjuno.ch/Content/logo/it/6639/BJ_Fattura_BLK.gif';
                break;
            case 'en':
                $logo = 'https://byjuno.ch/Content/logo/en/6639/BJ_Invoice_BLK.gif';
                break;
        }

        ?>
        <?php if (count($plans) > 1) { ?>
            <label style="padding: 0 0 10px 0"><?php echo Mage::getStoreConfig('payment/cdp/byjuno_invoice_payment_message', Mage::app()->getStore()) ?></label>
        <?php } else { ?>
            <br />
        <?php } ?>
        <table width="100%">
            <tr>
                <td style="vertical-align: middle; padding: 0 10px 0 0" width="70">
                    <?php echo '<img src="'.$logo.'" border="0" style="width:66px !important; max-width:66px !important" />'; ?>
                </td>
                <td style="vertical-align: middle" width="100%">
                    <span>
                        <?php
                        $i = 0;
                        if (count($plans) == 1) { ?>
                            <input type="hidden" name="payment[invoice_payment_plan]" value="<?php echo $this->htmlEscape($plans[0]["code"]) ?>"> <?php echo $this->htmlEscape($plans[0]["name"]); ?>
                            (<a href="<?php echo $this->htmlEscape($plans[0]["toc"]); ?>" target="_blank"><?php echo Mage::getStoreConfig('payment/cdp/byjuno_installment_toc_string', Mage::app()->getStore()) ?></a>)
                            <br />

                        <?php } else {
                            foreach($plans as $plan) { ?>
                                <input type="radio" <?php if ($i == 0) {
                                    echo 'checked="checked"';
                                } ?> name="payment[invoice_payment_plan]"
                                       value="<?php echo $this->htmlEscape($plan["code"]) ?>"> <?php echo $this->htmlEscape($plan["name"]); ?>
                                       (<a href="<?php echo $this->htmlEscape($plan["toc"]); ?>" target="_blank"><?php echo Mage::getStoreConfig('payment/cdp/byjuno_installment_toc_string', Mage::app()->getStore()) ?></a>)
                                <br/>
                                <?php
                                $i++;
                            }
                        } ?>
                    </span>
                </td>
            </tr>
            <?php if (Mage::getStoreConfig('payment/cdp/gender_enable', Mage::app()->getStore()) == '1') {
                $_gender = $this->getLayout()->createBlock('byjuno/widget_gender');
                ?>
                <tr>
                    <td>
                        <div class="field" style="width: 200px"><br />
                            <?php echo $_gender->setGender($quote->getCustomerGender())->setFieldIdFormat('payment:invoice_%s')->setFieldNameFormat('payment[invoice_%s]')->toHtml() ?>
                        </div>
                    </td>
                </tr>

            <?php } ?>
            <?php if (Mage::getStoreConfig('payment/cdp/birthday_enable', Mage::app()->getStore()) == '1') {
                $_dob = $this->getLayout()->createBlock('byjuno/widget_dobinvoice');
                ?>
                <tr>
                    <td>
                        <div class="field" style="width: 200px">
                            <?php echo $_dob->setDate($quote->getCustomerDob())->setFieldIdFormat('payment:invoice_%s')->setFieldNameFormat('payment[invoice_%s]')->toHtml(); ?>
                        </div>
                    </td>
                </tr>

            <?php } ?>
            <tr>
                <td colspan="2">
                    <div style="padding: 10px 0 5px 0">
                        <?php
                            if ($paperInvoice == 1) {
                            ?>
                                <input type="radio" checked="checked" name="payment[invoice_payment_send]" value="email"> Rechnungsversand via E-Mail (ohne Gebühr).<br/>
                                <input type="radio" name="payment[invoice_payment_send]" value="postal"> Rechnungsversand in Papierform via Post (gegen Gebühr von CHF 3.50 pro Rate).

                                <?php
                            } else {
                            ?>
                                <input type="hidden" name="payment[invoice_payment_send]" value="email"> Rechnungsversand via E-Mail (ohne Gebühr).
                            <?php
                            }
                        ?>
                    </div>
                </td>
            </tr>
            <tr>
                <td colspan="2" style="vertical-align: middle" width="100%">
					Customer communication language
                    <span>
                        <select name="payment[preffered_language]">
                            <option value="de"<?php if ($pref_lang == 'de') echo ' selected'; ?>>Deutsch</option>
                            <option value="fr"<?php if ($pref_lang == 'fr') echo ' selected'; ?>>Français</option>
                            <option value="it"<?php if ($pref_lang == 'it') echo ' selected'; ?>>Italiano</option>
                            <option value="en"<?php if ($pref_lang == 'en') echo ' selected'; ?>>English</option>
                        </select>
                    </span>
                </td>
            </tr>
        </table>
        <br />
    </div>
</div>