<div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <div><?php
        $locale = Mage::getStoreConfig('general/locale/code', Mage::app()->getStore());
        $locale = strstr($locale, "_", true);
        $lang = 'de';
        if ($locale == 'de' || $locale == 'fr' || $locale == 'it' || $locale == 'en') {
            $lang = $locale;
        }
        if ($locale)
        $pl = Mage::getStoreConfig('payment/cdp/byjuno_installment_payments', Mage::app()->getStore());
        $plns = explode(",", $pl);

        $stringValues = Array();
        $enablesValues = Array();

        $methodsAllowed["installment_3_enable"] = 0;
        $methodsAllowed["installment_10_enable"] = 1;
        $methodsAllowed["installment_12_enable"] = 2;
        $methodsAllowed["installment_24_enable"] = 3;
        $methodsAllowed["installment_4x12_enable"] = 4;
        $methodsAllowed["installment_4x10_enable"] = 5;

        $i = 0;
        foreach($plns as $val) {
            if (strstr($val, "_enable")) {
                $enablesValues[] = Array($val, $methodsAllowed[$val]);
            } else {
                $stringValues[$i] = $val;
                $i++;
            }
        }

        $i = 0;
        $plans = Array();
        foreach($enablesValues as $p) {
            $plans[] = Array("code" => $p[0], "name" => $stringValues[$p[1]], "toc" => $stringValues[$p[1] + 6]);
            $i++;
        }
        //http://byjuno.ch/Content/logo/de/6639/BJ_Ratenzahlung_BLK.gif

        $emailInstallment = Mage::getStoreConfig('payment/cdp/byjuno_installment_email', Mage::app()->getStore());
        $quote = Mage::getSingleton('checkout/type_onepage')->getQuote();


        ?>
        <?php if (count($plans) > 1) { ?>
            <label style="padding: 0 0 10px 0"><?php echo Mage::getStoreConfig('payment/cdp/byjuno_installment_payment_message', Mage::app()->getStore()) ?></label>
        <?php } else { ?>
            <br />
        <?php } ?>
        <table>
            <tr>
                <td style="vertical-align: middle; padding: 0 10px 0 0">
                     <?php echo '<img src="http://byjuno.ch/Content/logo/'.$lang.'/6639/BJ_Ratenzahlung_BLK.gif" border="0" />'; ?>
                </td>
                <td style="vertical-align: middle">
                    <span>
                        <?php
                        $i = 0;
                        if (count($plans) == 1) { ?>
                            <input type="hidden" name="payment[payment_plan]" value="<?php echo $this->htmlEscape($plans[0]["code"]) ?>"> <?php echo $this->htmlEscape($plans[0]["name"]); ?>
                            (<a href="<?php echo $this->htmlEscape($plans[0]["toc"]); ?>" target="_blank"><?php echo Mage::getStoreConfig('payment/cdp/byjuno_installment_toc_string', Mage::app()->getStore()) ?></a>)
                            <br />

                        <?php } else {
                            foreach($plans as $plan) { ?>
                                <input type="radio" <?php if ($i == 0) {
                                    echo 'checked="checked"';
                                } ?> name="payment[payment_plan]"
                                       value="<?php echo $this->htmlEscape($plan["code"]) ?>"> <?php echo $this->htmlEscape($plan["name"]); ?>
                                       (<a href="<?php echo $this->htmlEscape($plan["toc"]); ?>" target="_blank"><?php echo Mage::getStoreConfig('payment/cdp/byjuno_installment_toc_string', Mage::app()->getStore()) ?></a>)
                                <br/>
                                <?php
                                $i++;
                            }
                        } ?>
                    </span>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <div style="padding: 10px 0 5px 0">
                        <?php
                        if ($emailInstallment == 1) {
                            ?>
                            <input type="radio" checked="checked" name="payment[payment_send]" value="email"> <?php echo $this->htmlEscape(Mage::getStoreConfig('payment/cdp/byjuno_installment_email_text', Mage::app()->getStore())); ?>: <?php echo (String)$quote->getBillingAddress()->getEmail(); ?><br/>
                            <input type="radio" name="payment[payment_send]" value="postal"> <?php echo $this->htmlEscape(Mage::getStoreConfig('payment/cdp/byjuno_installment_postal_text', Mage::app()->getStore())); ?>: <?php echo (String)$quote->getBillingAddress()->getStreetFull(); ?>

                            <?php
                        } else {
                            ?>
                            <input type="hidden" name="payment[payment_send]" value="postal"> <?php echo $this->htmlEscape(Mage::getStoreConfig('payment/cdp/byjuno_installment_postal_text', Mage::app()->getStore())); ?>
                            <?php
                        }
                        ?>
                    </div>
                </td>
            <tr>
        </table>
        <br />
    </div>
</div>