<?php
if (Mage::getStoreConfig('byjuno/api/tmxenabled', Mage::app()->getStore()) == 'enable'
    && Mage::getStoreConfig('byjuno/api/tmxkey', Mage::app()->getStore()) != ''
    && Mage::getStoreConfig('byjuno/api/pluginenabled', Mage::app()->getStore()) == 'enable') {
    $sesId = Mage::getSingleton('checkout/session')->getEncryptedSessionId();
    $tmkKey = Mage::getStoreConfig('byjuno/api/tmxkey', Mage::app()->getStore());
    Mage::getSingleton('checkout/session')->setData("byjuno_session_id", $sesId);
    echo '
    <script type="text/javascript" src="https://h.online-metrix.net/fp/tags.js?org_id='.$tmkKey.'&session_id='.$sesId.'&pageid=checkout"></script>
<noscript>
<iframe style="width: 100px; height: 100px; border: 0; position: absolute; top: -5000px;" src="https://h.online-metrix.net/tags?org_id='.$tmkKey.'&session_id='.$sesId.'&pageid=checkout"></iframe>
</noscript>
    ';
}