<?php
if (Mage::getStoreConfig('payment/cdp/tmxenabled', Mage::app()->getStore()) == '1'
    && Mage::getStoreConfig('payment/cdp/tmxkey', Mage::app()->getStore()) != ''
    && Mage::getStoreConfig('payment/cdp/active', Mage::app()->getStore()) == '1') {
    $sesId = Mage::getSingleton('checkout/session')->getEncryptedSessionId();
    $tmkKey = Mage::getStoreConfig('payment/cdp/tmxkey', Mage::app()->getStore());
    Mage::getSingleton('checkout/session')->setData("byjuno_session_id", $sesId);
    echo '
    <script type="text/javascript" src="https://h.online-metrix.net/fp/tags.js?org_id='.$tmkKey.'&session_id='.$sesId.'&pageid=checkout"></script>
<noscript>
<iframe style="width: 100px; height: 100px; border: 0; position: absolute; top: -5000px;" src="https://h.online-metrix.net/tags?org_id='.$tmkKey.'&session_id='.$sesId.'&pageid=checkout"></iframe>
</noscript>
    ';
}